version: '3.8'

services:
  app:
    image: annapurna-app
    container_name: annapurna-app
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: annapurnadb
      MYSQL_USER: annapurna
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

